heat_template_version: 2016-04-08

description: >
  MidoNet Agent service deployment using Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  AdminPassword:
    description: The password for the keystone admin account, used to query neutron
    type: string
    hidden: true
  MidonetAgentMetadataPort:
    default: "8775"
    description: "Port on which the metadata service is listening"
    type: string
  NeutronMetadataProxySharedSecret:
    description: Shared secret to prevent spoofing
    type: string
    hidden: true
  TunnelZoneType:
    default: 'vxlan'
    description: 'Type of the tunnels on the overlay. Choose between `gre` and `vxlan`'
    type: string
  MidonetAgentMaxHeapSize:
    default: '2048M'
    description: 'Amount of heap memory the JVM will use to run the MidoNet Agent'
    type: string

resources:
  MidonetBase:
    type: ./midonet-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the MidoNet Agent service
    value:
      service_name: midonet_agent
      config_settings:
        map_merge:
          - get_attr: [MidonetBase, role_data, config_settings]
          - tripleo::network::midonet::agent::tunnelzone_type: {get_param: TunnelZoneType}
            tripleo::network::midonet::agent::metadata_port: {get_param: MidonetAgentMetadataPort}
            tripleo::network::midonet::agent::shared_secret: {get_param: NeutronMetadataProxySharedSecret}
            tripleo::network::midonet::agent::manage_repo: false
            tripleo::network::midonet::agent::username: 'admin'
            tripleo::network::midonet::agent::password: {get_param: AdminPassword}
            tripleo::network::midonet::agent::max_heap_size: {get_param: MidonetAgentMaxHeapSize}
            tripleo::network::midonet::agent::controller_host: '"%{hiera(''nova_metadata_vip'')}"'
            tripleo::network::midonet::agent::cluster_endpoint: {get_param: [EndpointMap, MidonetClusterInternal, uri]}
            tripleo::network::midonet::agent::tenant_name: 'admin'
            tripleo.midonet_agent.firewall_rules:
              '300 MidoNet Agent (Metadata)':
                iniface: 'metadata'
                proto: 'all'
                action: 'accept'
              '301 MidoNet Agent (VXLAN)':
                proto: 'udp'
                dport: 4789
              '302 MidoNet Agent (VXLAN)':
                proto: 'udp'
                dport: 5123
              '303 MidoNet Agent (VXLAN)':
                proto: 'udp'
                dport: 6677
              '304 MidoNet Agent (VXLAN)':
                proto: 'udp'
                dport: 8899
              '310 MidoNet Agent (VXLAN)':
                chain: 'FORWARD'
                proto: 'udp'
                dport: 4789
              '311 MidoNet Agent (VXLAN)':
                chain: 'FORWARD'
                proto: 'udp'
                dport: 5123
              '312 MidoNet Agent (VXLAN)':
                chain: 'FORWARD'
                proto: 'udp'
                dport: 6677
              '313 MidoNet Agent (VXLAN)':
                chain: 'FORWARD'
                proto: 'udp'
                dport: 8899
              '314 MidoNet Agent Metadata Proxy':
                proto: 'tcp'
                dport: 9697
              '315 MidoNet Agent JMX monitoring':
                proto: 'tcp'
                dport: 7200
      step_config: |
        include ::tripleo::network::midonet::agent
