heat_template_version: 2015-04-30

description: >
  MidoNet Enterprise Manager (MEM) service deployment using Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MemUseSsl:
    default: false
    description: 'Whether to use SSL or not'
    type: boolean

resources:
  MidonetBase:
    type: ./midonet-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the MidoNet Enterprise Manager (MEM) service
    value:
      service_name: midonet_mem
      config_settings:
        map_merge:
          - get_attr: [MidonetBase, role_data, config_settings]
          - tripleo::network::midonet::mem::cluster_ip: '"%{hiera(''midonet_cluster_vip'')}"'
            tripleo::network::midonet::mem::analytics_ip: '"%{hiera(''midonet_analytics_vip'')}"'
            tripleo::network::midonet::mem::is_ssl: {get_param: MemUseSsl}
      step_config: |
        include ::tripleo::network::midonet::mem
