heat_template_version: 2016-04-08

description: >
  MidoNet Cluster (formerly known as MidoNet API) service deployment using Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MidonetClusterUsername:
    default: "admin"
    description: Keystone user to be used for authentication (must have
                 the admin role)
    type: string
  MidonetClusterPassword:
    description: The password for the keystone user that will be used by
                 the MidoNet Cluster.
    type: string
    hidden: true
  MidonetClusterTenant:
    default: "service"
    description: Keystone tenant to be used for authentication
    type: string
  AdminPassword:
    description: The password for the keystone admin account, used to query neutron
    type: string
    hidden: true

resources:
  MidonetBase:
    type: ./midonet-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Service MidoNet Cluster using composable services
    value:
      service_name: midonet_cluster
      config_settings:
        map_merge:
          - get_attr: [MidonetBase, role_data, config_settings]
          - tripleo::network::midonet::cluster::keystone_user_name: {get_param: MidonetClusterUsername}
            tripleo::network::midonet::cluster::keystone_user_password: {get_param: AdminPassword}
            tripleo::network::midonet::cluster::keystone_tenant_name: {get_param: MidonetClusterTenant}
            tripleo.midonet_cluster.firewall_rules:
              '333 midonet_cluster':
                dport:
                  - 8181
      step_config: |
        include ::tripleo::network::midonet::cluster
