heat_template_version: 2016-04-08

description: >
  MidoNet Enterprise Manager (MEM) service deployment using Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MemUseSsl:
    default: false
    description: 'Whether to use SSL or not'
    type: boolean
  MemAnalyticsPort:
    default: ":8080"
    description: The port where the midonet analytics is listening.
    type: string
  MemApiNamespace:
    default: "midonet-api"
    description: Namespace for the MidoNet Cluster (used to configure Apache).
    type: string
  MemTraceNamespace:
    default: "trace"
    description: Namespace for the MidoNet Traces (used to configure Apache).
    type: string
  MemAnalyticsNamespace:
    default: "analytics"
    description: Namespace for the MidoNet Analytics (used to configure Apache).
    type: string
  MemPackageName:
    default: "midonet-manager"
    description: Name of the MEM package.
    type: string
  MemInstallPath:
    default: "/var/www/html/midonet-manager"
    description: Path where the MEM package is installed.
    type: string
  MemApiVersion:
    default: "5.4"
    description: The default value for the api_version is set to latest version.
                 In case you are using and older MidoNet REST API, change the
                 version accordingly.
    type: string
  MemApiToken:
    default: false
    description: If desired, auto-login can be enabled by setting the value of
                 api_token to your Keystone token.
    type: string
  MemAgentConfigApiNamespace:
    default: "conf"
    description: The default value for the api_namespace is set to conf which
                 usually does not have to be changed.
    type: string
  MemPollEnabled:
    default: true
    description: The Auto Polling will seamlessly refresh Midonet Manager data
                 periodically. It is enabled by default and can be disabled in
                 Midonet Manager's Settings section directly through the UI.
                 This will only disable it for the duration of the current
                 session. It can also be disabled permanently by changing the
                 `poll_enabled` parameter to `false`.
    type: boolean
  MemLoginAnimationEnabled:
    default: true
    description: Whether the login page background animation should be enabled
                 or not.
    type: boolean
  MemConfigFile:
    default: "/var/www/html/midonet-manager/config/client.js"
    description: Path where the MEM configuration file can be found.
    type: string
  MemApacheDocroot:
    default: ''
    description: Apache document root used in the MEM vhost.
    type: string
  MemApachePort:
    default: ''
    description: Port on which the MEM virtualhost listens.
    type: string
  MemProxyPreserveHost:
    default: ''
    description: Whether Apache should preserve the original host in the Host
                 header.
    type: string
  MemSslCert:
    default: ''
    description: Path where the SSL certificate is.
    type: string
  MemSslKey:
    default: ''
    description: Path where the SSL key can be found.
    type: string
  MemInsightsSsl:
    default: false
    description: Set to `true` if Insights is configured to work with SSL
                 enabled.
    type: boolean
  MemApiPort:
    default: ":8181"
    description: The port where the MidoNet API is listening.
    type: string
  MemTracePort:
    default: ":8460"
    description: The port where the MidoNet Traces service is listening.
    type: string
  MemSubscriptionPort:
    default: ":8007"
    description: Port where the MidoNet Subscription service is listening.
    type: string
  MemFabricPort:
    default: ":8009"
    description: The port where the MidoNet Fabric service will listen.
    type: string
  MemApiSsl:
    default: false
    description: Enable if the MidoNet API is using SSL.
    type: boolean

resources:
  MidonetBase:
    type: ./midonet-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the MidoNet Enterprise Manager (MEM) service
    value:
      service_name: midonet_mem
      config_settings:
        map_merge:
          - get_attr: [MidonetBase, role_data, config_settings]
          - tripleo::network::midonet::mem::cluster_ip: '"%{hiera(''midonet_cluster_vip'')}"'
            tripleo::network::midonet::mem::analytics_ip: '"%{hiera(''midonet_analytics_vip'')}"'
            tripleo::network::midonet::mem::is_ssl: {get_param: MemUseSsl}
            tripleo::network::midonet::mem::mem_analytics_port: {get_param: MemAnalyticsPort}
            tripleo::network::midonet::mem::mem_api_namespace: {get_param: MemApiNamespace}
            tripleo::network::midonet::mem::mem_trace_namespace: {get_param: MemTraceNamespace}
            tripleo::network::midonet::mem::mem_analytics_namespace: {get_param: MemAnalyticsNamespace}
            tripleo::network::midonet::mem::mem_package: {get_param: MemPackageName}
            tripleo::network::midonet::mem::mem_install_path: {get_param: MemInstallPath}
            tripleo::network::midonet::mem::mem_api_version: {get_param: MemApiVersion}
            tripleo::network::midonet::mem::mem_api_token: {get_param: MemApiToken}
            tripleo::network::midonet::mem::mem_agent_config_api_namespace: {get_param: MemAgentConfigApiNamespace}
            tripleo::network::midonet::mem::mem_poll_enabled: {get_param: MemPollEnabled}
            tripleo::network::midonet::mem::mem_login_animation_enabled: {get_param: MemLoginAnimationEnabled}
            tripleo::network::midonet::mem::mem_config_file: {get_param: MemConfigFile}
            tripleo::network::midonet::mem::mem_apache_docroot: {get_param: MemApacheDocroot}
            tripleo::network::midonet::mem::mem_apache_port: {get_param: MemApachePort}
            tripleo::network::midonet::mem::mem_proxy_preserve_host: {get_param: MemProxyPreserveHost}
            tripleo::network::midonet::mem::ssl_cert: {get_param: MemSslCert}
            tripleo::network::midonet::mem::ssl_key: {get_param: MemSslKey}
            tripleo::network::midonet::mem::insights_ssl: {get_param: MemInsightsSsl}
            tripleo::network::midonet::mem::mem_api_port: {get_param: MemApiPort}
            tripleo::network::midonet::mem::mem_trace_port: {get_param: MemTracePort}
            tripleo::network::midonet::mem::mem_subscription_port: {get_param: MemSubscriptionPort}
            tripleo::network::midonet::mem::mem_fabric_port: {get_param: MemFabricPort}
            tripleo::network::midonet::mem::api_ssl: {get_param: MemApiSsl}
            tripleo::network::midonet::mem::
      step_config: |
        include ::tripleo::network::midonet::mem
